config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  get '/user_show', to: 'pages#user_show'
  get '/mentionslegales', to: 'pages#mentionslegales'
  get '/conditionsgenerales', to: 'pages#conditionsgenerales'
  get '/apropos', to: 'pages#apropos'
  get '/nostarifs', to: 'pages#nostarifs'

  resources :contacts, only: [:new, :create]
  resources :users, only: [:update]
  get :order_confirmation, to: 'orders#order_confirmation'
  resources :orders, only: [ :index, :destroy, :update, :edit ]
  resources :packs, only: [ :index, :show ] do
    resources :orders, only: [ :show, :create ] do
    end
  end
  get '/cart_confirmation', to: 'carts#cart_confirmation'
  resources :carts, only: [:show]
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image:
 url(<%= image_path 'pack.png' %>);">
 <div class="color_overlay_banner"></div>
  <div class="banner-content">
    <h1> Timply </h1>
    <h2> La solution pour réduire vos coûts d'envoi ! </h2>
    <%= link_to 'Commander',packs_path, class: "btn btn-cta center-block" %>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div id="testimonial-slider" class="owl-carousel">
                <div class="testimonial">
                    <div class="testimonial-content">
                        <div class="testimonial-icon">
                            <i class="fa fa-quote-left"></i>
                        </div>
                        <p class="description">
                            Service 100% fiable, de bonne qualité, un gérant adorable ! Je recommande à tous ceux qui ont besoin de poster des lettres pour un prix moins cher que la Poste.
                        </p>
                    </div>
                    <h3 class="title">Sharon</h3>
                    <span class="post">Wedding Planner</span>
                </div>
                <div class="testimonial">
                    <div class="testimonial-content">
                        <div class="testimonial-icon">
                            <i class="fa fa-quote-left"></i>
                        </div>
                        <p class="description">Un an que nous travaillons avec Timply. Serieux, ponctuel, c'est plus de 2000 lettre suivie par semaine envoyé rapidement et moins cher.
                        </p>
                    </div>
                    <h3 class="title">Celia</h3>
                    <span class="post">Gérante E-commerce </span>
                </div>
                <div class="testimonial">
                    <div class="testimonial-content">
                        <div class="testimonial-icon">
                            <i class="fa fa-quote-left"></i>
                        </div>
                        <p class="description">
                            Rapide, fiable, vous avez non seulement des beaux timbres mais en plus le service qui va avec, je recommande !
                        </p>
                    </div>
                    <h3 class="title">Julien</h3>
                    <span class="post">Responsable admnistratif en assurance</span>
                </div>
                <div class="testimonial">
                    <div class="testimonial-content">
                        <div class="testimonial-icon">
                            <i class="fa fa-quote-left"></i>
                        </div>
                        <p class="description">
                            Timply est un service simple à utiliser, très efficace et disponible au moindre appel. <br>
                            Je les conseille fortement
                        </p>
                    </div>
                    <h3 class="title">Leo</h3>
                    <span class="post">Gérant E-commerce</span>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js"></script>
<script>
    $(document).ready(function() {
        $("#testimonial-slider").owlCarousel({
            items: 3,
            itemsDesktop: [1000, 3],
            itemsDesktopSmall: [980, 2],
            itemsTablet: [768, 2],
            itemsMobile: [650, 1],
            pagination: true,
            navigation: false,
            slideSpeed: 1000,
            autoPlay: true
        });
    });
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="foot-image">
    <%= link_to root_path do %>
      <%= image_tag "logo.png", height: 80 %>
    <% end %>
    <p>©2018 Timply</p>
  </div>
  <div class="footer-service">
    <ul>
      <h6><strong>NOTRE SERVICE </strong></h6>
      <li><%= link_to 'Nos packs',packs_path %> </li>
      <li>   <%= link_to 'Nos tarifs', asset_path("timply2.pdf"), :target => "_blank" %> </li>
    </ul>
  </div>
  <div class="a-propos">
    <ul>
      <h6><strong> A PROPOS </strong></h6>
      <li>     <%= link_to 'Notre mission', apropos_path %></li>
      <li><%= link_to 'Conditions Générales', conditionsgenerales_path %> </li>
      <li><%= link_to 'Mentions légales', mentionslegales_path %> </li>

    </ul>
  </div>
  <div class="liens-utiles">
    <ul>
      <h6><strong>LIENS UTILES </strong></h6>
      <li><a href="http://www.estrepublicain.fr/insolite/2012/01/10/en-franc-mais-toujours-valables" target="_blank">Timbres de collections </a></li>
      <li><%= link_to 'Accéder à mes commandes', dashboard_path %></li>
        <li><a href="https://fr.depositphotos.com/194625712/stock-illustration-international-standard-envelopes-for-paper.html" target="_blank">Formats d'enveloppes </a></li>
    </ul>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_gallery.html.erb
<div class="container spec">
  <h1 class="heading text-center">Nos enveloppes</h1>
  <div class="gallery">
    <div class="gallery-item">
      <img class="gallery-image" src="https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=500&h=500&fit=crop" alt="person writing in a notebook beside by an iPad, laptop, printed photos, spectacles, and a cup of coffee on a saucer">
    </div>
    <div class="gallery-item">
      <div class="gallery-image">
      <%= image_tag"vrac-timbre.png" %>
      </div>
    </div>
    <div class="gallery-item">
      <img class="gallery-image" src="https://images.unsplash.com/photo-1506045412240-22980140a405?w=500&h=500&fit=crop" alt="people holding umbrellas on a busy street at night lit by street lights and illuminated signs in Tokyo, Japan">
    </div>
    <div class="gallery-item">
      <img class="gallery-image" src="https://images.unsplash.com/photo-1514041181368-bca62cceffcd?w=500&h=500&fit=crop" alt="car interior from central back seat position showing driver and blurred view through windscreen of a busy road at night">
    </div>
    <div class="gallery-item">
      <img class="gallery-image" src="https://images.unsplash.com/photo-1445810694374-0a94739e4a03?w=500&h=500&fit=crop" alt="back view of woman wearing a backpack and beanie waiting to cross the road on a busy street at night in New York City, USA">
    </div>
    <div class="gallery-item">
      <img class="gallery-image" src="https://images.unsplash.com/photo-1486334803289-1623f249dd1e?w=500&h=500&fit=crop" alt="man wearing a black jacket, white shirt, blue jeans, and brown boots, playing a white electric guitar while sitting on an amp">
    </div>
  </div>
</div>

app/views/shared/_modal_sign_in.html.erb
<!-- Modal -->
<div class="modal fade" id="elegantModalForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <!--Content-->
    <div class="modal-content form-elegant">
      <!--Header-->
      <div class="modal-header text-center">
        <h3 class="modal-title w-100 dark-grey-text font-weight-bold my-3" id="myModalLabel"><strong>Se connecter</strong></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!--Body-->
      <div class="modal-body mx-4">
        <!--Body-->
       <%= simple_form_for(@instance_user, url: session_path(@instance_user)) do |f| %>
  <%= f.error_notification %>
 <div class="form-inputs">
    <%= f.input :email,
                required: false,
                autofocus: true,
                input_html: { autocomplete: "email" } %>
    <%= f.input :password,
                required: false,
                input_html: { autocomplete: "current-password" } %>

  </div>

  <div class="form-actions">
    <%= f.button :submit,  "Connexion",class: "btn-modal"%>
  </div>
<% end %>


      </div>
      <!--Footer-->
      <div class="modal-footer mx-5 pt-3 mb-1">
        <p class="font-small grey-text d-flex justify-content-end">Pas encore membre ?
          <%= link_to "Inscrivez-vous", new_user_registration_path, class: "blue-text ml-1" %> </p>
      </div>
    </div>
    <!--/.Content-->
  </div>
</div>
<!-- Modal -->
      <li class="nav-item">
<a href="" class="nav-link" data-toggle="modal" data-target="#elegantModalForm">Connexion</a>

      </li>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <% @instance_user = User.new %>
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to 'Nos tarifs', nostarifs_path, class: " nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Notre mission', apropos_path, class: " nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Contactez-nous', new_contact_path, class: " nav-link" %>
            </li>
            <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Suivi de vos envois', 'https://packsdenveloppes.aftership.com/', class: " nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to cart_path(current_user.cart), class: "nav-link" do %>
                <i class="fas fa-shopping-cart"></i>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to 'Commander', packs_path, class: " btn btn-cta-nav center-block navbar-wagon-item navbar-wagon-link ml-2 btn-nav-mobile" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Mes commandes', dashboard_path, class:"btn btn-nav center-block navbar-wagon-item navbar-wagon-link mr-3 btn-nav-mobile" %>
            </li>
            <li class="nav-item">
                <%= link_to "Administrateur", orders_path, class: "nav-link" if current_user.admin %>
            </li>
            <li class="nav-item dropdown">
                <%= image_tag "default_avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <%= link_to cart_path(current_user.cart), class: "dropdown-item" do %>
                    <i class="fas fa-shopping-cart"></i> <%= "Mon Panier" %>
                    <% end %>
                    <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                    <i class="fa fa-cog"></i> <%= t(".settings", default: "Profile") %>
                    <% end %>
                    <%= link_to packs_path, class: "dropdown-item" do %>
                    <i class="fas fa-envelope"></i> Commander
                    <% end %>
                    <%= link_to "Mes commandes", dashboard_path, class: "dropdown-item" %>
                    <%= link_to "Contactez-nous", new_contact_path, class: "dropdown-item" %>
                    <%= link_to "Notre mission", apropos_path, class: "dropdown-item" %>
                    <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                    <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Se deconnecter") %>
                    <% end %>
                </div>
            </li>
            <% else %>
            <%= render 'shared/modal_sign_in' %>
            <li class="nav-item">
                <%= link_to 'Commander', packs_path, class: " btn btn-cta-nav center-block navbar-wagon-item navbar-wagon-link ml-2 btn-nav-mobile" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Inscription', new_user_registration_path, class:"btn btn-nav center-block nav-link" %>
                <% end %>
        </ul>
    </div>
</div>