config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  get '/user_show', to: 'pages#user_show'
  get '/mentionslegales', to: 'pages#mentionslegales'
  get '/conditionsgenerales', to: 'pages#conditionsgenerales'
  get '/apropos', to: 'pages#apropos'
  get '/nostarifs', to: 'pages#nostarifs'

  resources :contacts, only: [:new, :create]
  resources :users, only: [:update]
  get :order_confirmation, to: 'orders#order_confirmation'
  resources :orders, only: [ :index, :destroy, :update, :edit ]
  resources :packs, only: [ :index, :show ] do
    resources :orders, only: [ :show, :create ] do
    end
  end
  get '/cart_confirmation', to: 'carts#cart_confirmation'
  resources :carts, only: [:show]
end

app/models/pack.rb
class Pack < ApplicationRecord
  has_many :orders
  serialize :category
end

app/controllers/packs_controller.rb
PCK = {"Lettre Verte": ["0.87", "0.97"],
       "Lettre Prioritaire": ["0.94","1.05"],
       "Lettre Suivie": ["1.27","1.45"],
       "Recommandées": ["3.87","4.30"]}


class PacksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @packs = Pack.all
  end

  def show
    @poids = ["20g", "100g", "250g", "500g", "3kg"]
    @pack = Pack.find(params[:id])
    @packs = Pack.where.not(id:@pack.id)
    @show_prices = [PCK[@pack.title.to_sym][0], PCK[@pack.title.to_sym][1]]
    @order = Order.new
  end
end

app/views/packs/index.html.erb
<body class="banner-inscription" style="background: linear-gradient(#0052D4, #4364F7,#6FB1FC);
 url(<%= image_path 'banner2.png' %>);">


<div class="flex-product">
   <h1 class="text-center" style="color: white"> Nos packs d'enveloppes pré-timbrées </h1>
  <div class="container">


    <div class="row">




        <% @packs.each do |pack|  %>
      <div class="col-xs-12 col-md-3  ">
<div class="cardproduit ">
  <div class="cardproduit-img" style="background-image:url(https://i.ibb.co/ZYTRSrw/minipack.jpg);">
    <div class="overlay">
      <div class="overlay-content">
         <%= link_to pack.title, pack_path(pack) %>
      </div>
    </div>
  </div>

  <div class="cardproduit-content">
    <a href="#!">
      <h2><%= pack.title %></h2>
      <p>Économisez jusqu'a 20% sur vos envois.</p>

    </a>
  </div>
</div>
</div>







        <% end %>
      </div>
    </div>
  </div>

</body>

app/views/packs/show.html.erb
<div class="body" style="background: linear-gradient(#0052D4, #4364F7,#6FB1FC);">
  <div class="container">

      <div class="row ">
        <div class="col-xs-12 col-sm-6 col-md-7 mt-5">
          <div class="a ">
            <%= image_tag(@pack.photo)%>
            <div class="detail text-center">
              <h4 > <strong> Details : </strong> </h4>
              <p>  <%= @pack.infos %></p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-5 mt-5">
          <div class="card_form text-center">
            <div class="price">
              <h1> <%= @show_prices[0]%>€ </h1>
              <h3> <%= @show_prices[1] %>€</h3>
            </div>
            <div class="form-group decal">
              <%= simple_form_for([@pack, @order])do |f| %>
                <div class="form-row">
                  <div class="col-xs-12 col-md-9">
                    <%= f.input :category, collection: @pack.category, label: "Type d'envoi", required: true %>
                    <%= f.input :quantity, label: "Quantité", required: true %>
                    <%= f.input :weight, collection: ["20g","100g", "250g", "500g","3kg"],label: "Poids", required: true %>
                    <%= f.input :format, collection: ["DL(stantard)","C4","C5","C6"],label: "Format d'enveloppe", required: true %>
                    <%= f.input :ar, label: "AR" if @pack.title == "Recommandés"%>
                    <%= f.input :pb, label: "Papier Bulle"%>
                    <%= f.button :submit,"Recevoir mes prix",class: " btn-form "%>
                  <% end %>
                </div>
              </div>

            </div>

          </div>
        </div>
      </div>

  </div>
  <h1 class="text-center margin2"> Nos autres produits </h1>
  <div class="container ">
    <div class="row">
      <% @packs.each do |pack| %>
        <div class="col-xs-12 col-sm-6 col-md-4
        ">
          <div class=" b ">
            <%= link_to image_tag(pack.photo), pack_path(pack)%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%=render'shared/footer'%>